# Generated by Django 4.2.7 on 2023-11-15 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, choices=[('Apicultura', 'Apicultura'), ('ADS', 'ADS'), ('Alimentos', 'Alimentos'), ('Quimica', 'Química')], max_length=100, null=True, verbose_name='Curso:')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=250, null=True, verbose_name='Rua:')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número:')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade:')),
                ('sigla_estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome do Aluno')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade:')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.curso', verbose_name='Curso')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.endereco', verbose_name='Endereço do aluno')),
            ],
        ),
    ]
