# Generated by Django 4.2.6 on 2023-10-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sebo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=200)),
                ('selo_fonografico', models.CharField(blank=True, max_length=50)),
                ('ano', models.IntegerField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=200)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('quantidade', models.IntegerField(blank=True)),
            ],
        ),
    ]
