# Generated by Django 4.2.6 on 2023-10-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsExample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sebo',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de lançamento'),
        ),
        migrations.AlterField(
            model_name='sebo',
            name='descricao',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição do Álbum'),
        ),
        migrations.AlterField(
            model_name='sebo',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gênero musical'),
        ),
        migrations.AlterField(
            model_name='sebo',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Artista'),
        ),
        migrations.AlterField(
            model_name='sebo',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='País de lançamento'),
        ),
        migrations.AlterField(
            model_name='sebo',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de cópias'),
        ),
        migrations.AlterField(
            model_name='sebo',
            name='selo_fonografico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Noma da Gravadora'),
        ),
    ]
