# Generated by Django 4.2.6 on 2023-10-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsExample', '0002_alter_sebo_ano_alter_sebo_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeloFonografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selo_fonografico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Noma da Gravadora')),
            ],
        ),
        migrations.RemoveField(
            model_name='sebo',
            name='selo_fonografico',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(blank=True, max_length=200, verbose_name=' Qual o numero de votos')),
                ('votes', models.IntegerField(blank=True, verbose_name='Número de votos')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsExample.sebo', verbose_name='Questão')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='nome do artista')),
                ('disco', models.ManyToManyField(blank=True, null=True, to='modelsExample.sebo')),
            ],
        ),
        migrations.AddField(
            model_name='sebo',
            name='selo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelsExample.selofonografico'),
        ),
    ]
