# Generated by Django 4.2.6 on 2023-10-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsExample', '0003_selofonografico_remove_sebo_selo_fonografico_choice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
