# Generated by Django 4.2.6 on 2023-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_aluno_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade:'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='sigla_estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Curso:'),
        ),
    ]
